fix: Age-old bug that prevented a full start over.
Summarizing it, it caused this fatal error message:

"
WARN: dd failed to write 62914560 blocks to /run/media/luiz/Novo Volume/Copa.img.
WARN: It possible reported an error and/or an interruption signal before this message.
ERROR: Please, check. Stopping the build process.
"

Looking from another angle, it was a nice security mechanism.
I hope I don't regret fixing it --- nor that I need to improve
it anytime soon.